const tags = {
    "namespaces": {
    "caas": {
    "name": "caas",
    "title": "CaaS",
    "description": "",
    "path": "/content/cq:tags/caas",
    "tags": {
    "content-type": {
    "path": "/content/cq:tags/caas/content-type",
    "tagID": "caas:content-type",
    "name": "content-type",
    "tagImage": "",
    "title": "Content Type",
    "title.de": "Inhaltstyp",
    "title.zh_cn": "内容类型",
    "title.es": "Tipo de contenido",
    "title.pt": "Tipo de conteúdo",
    "title.fr": "Type de contenu",
    "title.sv": "Innehållstyp",
    "title.ja": "コンテンツの種類",
    "title.zh_hk": "內容類型",
    "title.zh_tw": "內容類型",
    "title.it": "Tipo di contenuto",
    "title.ko": "콘텐츠 유형",
    "title.nl": "Type Inhoud",
    "description": "",
    "cq:movedTo": "",
    "tags": {
    "report": {
    "path": "/content/cq:tags/caas/content-type/report",
    "tagID": "caas:content-type/report",
    "name": "report",
    "tagImage": "",
    "title": "Report",
    "title.de": "Bericht",
    "title.zh_cn": "报告",
    "title.es": "Informe",
    "title.pt": "relatório",
    "title.fr": "Rapport ",
    "title.sv": "Rapport",
    "title.ja": "レポート",
    "title.zh_tw": "報告",
    "title.it": "Report",
    "title.ko": "보고서",
    "title.nl": "Rapport",
    "description": ".",
    "cq:movedTo": "",
    "tags": {}
    },
    "customer-story": {
    "path": "/content/cq:tags/caas/content-type/customer-story",
    "tagID": "caas:content-type/customer-story",
    "name": "customer-story",
    "tagImage": "",
    "title": "Customer Story",
    "title.de": "Kundenreferenz",
    "title.zh_cn": "客户案例",
    "title.es": "Historia de cliente",
    "title.pt": "Case de sucesso",
    "title.fr": "Témoignage client",
    "title.sv": "Kundberättelse",
    "title.ja": "ユーザー事例",
    "title.zh_tw": "客戶故事",
    "title.it": "Testimonianza del cliente",
    "title.ko": "고객 사례",
    "title.nl": "Klantverhaal",
    "title.th": "เรื่องราวของลูกค้า",
    "description": "",
    "cq:movedTo": "",
    "tags": {}
    },
    "video": {
    "path": "/content/cq:tags/caas/content-type/video",
    "tagID": "caas:content-type/video",
    "name": "video",
    "tagImage": "",
    "title": "Video",
    "title.sv_se": "Video",
    "title.zh_cn": "视频",
    "title.ko_kr": "영상",
    "title.pt": "Vídeo",
    "title.nl_nl": "Video",
    "title.fr": "Vidéo",
    "title.ja": "ビデオ",
    "title.zh_hk": "視訊",
    "title.zh_tw": "視訊",
    "title.it": "Video",
    "title.ko": "영상",
    "title.de": "Video",
    "title.es": "Vídeo",
    "title.sv": "Video",
    "title.nl": "Video",
    "title.th": "วิดีโอ",
    "description": "",
    "cq:movedTo": "",
    "tags": {}
    },
    "article": {
    "path": "/content/cq:tags/caas/content-type/article",
    "tagID": "caas:content-type/article",
    "name": "article",
    "tagImage": "",
    "title": "Article",
    "title.de": "Artikel",
    "title.zh_cn": "文章",
    "title.es": "Artículo",
    "title.pt": "Artigo",
    "title.fr": "Article",
    "title.sv": "Artikel",
    "title.ja": "記事",
    "title.zh_tw": "文章",
    "title.it": "Articolo",
    "title.ko": "기사",
    "title.nl": "Artikel",
    "title.th": "บทความ",
    "description": "",
    "cq:movedTo": "",
    "tags": {}
    },
    "blog": {
    "path": "/content/cq:tags/caas/content-type/blog",
    "tagID": "caas:content-type/blog",
    "name": "blog",
    "tagImage": "",
    "title": "Blog",
    "title.de": "Blog",
    "title.zh_cn": "博客",
    "title.es": "Blog",
    "title.pt": "Blog",
    "title.fr": "Blog",
    "title.sv": "Blogg",
    "title.ja": "ブログ",
    "title.zh_tw": "部落格",
    "title.it": "Blog",
    "title.ko": "블로그",
    "title.nl": "Blog",
    "title.th": "บล็อก",
    "description": "",
    "cq:movedTo": "",
    "tags": {}
    },
    "documentation": {
    "path": "/content/cq:tags/caas/content-type/documentation",
    "tagID": "caas:content-type/documentation",
    "name": "documentation",
    "tagImage": "",
    "title": "Documentation",
    "title.de": "Dokumentation",
    "title.zh_cn": "文档",
    "title.es": "Documentación",
    "title.pt": "Documentação",
    "title.fr": "Documentation",
    "title.sv": "Dokumentation",
    "title.ja": "ドキュメント",
    "title.zh_tw": "文件",
    "title.it": "Documentazione",
    "title.ko": "설명서",
    "title.nl": "Documentatie",
    "title.th": "เอกสาร",
    "description": "",
    "cq:movedTo": "",
    "tags": {}
    },
    "webinar": {
    "path": "/content/cq:tags/caas/content-type/webinar",
    "tagID": "caas:content-type/webinar",
    "name": "webinar",
    "tagImage": "",
    "title": "Webinar",
    "title.sv_se": "Webbinarium",
    "title.zh_cn": "网络讲座",
    "title.ko_kr": "웨비나",
    "title.pt": "Webinário",
    "title.nl_nl": "Webinar",
    "title.fr": "Webinaire",
    "title.ja": "ウェビナー",
    "title.zh_hk": "網路研討會",
    "title.zh_tw": "網路研討會",
    "title.it": "Webinar",
    "title.ko": "온라인 세미나",
    "title.de": "Webinar",
    "title.es": "Seminario web",
    "title.sv": "Webbinarium",
    "title.nl": "Webinar",
    "title.th": "การสัมมนาผ่านเว็บ",
    "description": "",
    "cq:movedTo": "",
    "tags": {}
    },
    "quiz": {
    "path": "/content/cq:tags/caas/content-type/quiz",
    "tagID": "caas:content-type/quiz",
    "name": "quiz",
    "tagImage": "",
    "title": "Quiz",
    "title.de": "Quiz",
    "title.zh_cn": "测试",
    "title.es": "Cuestionario",
    "title.pt": "Teste",
    "title.fr": "Questionnaire",
    "title.sv": "Quiz",
    "title.ja": "クイズ",
    "title.zh_tw": "測驗",
    "title.it": "Questionario",
    "title.ko": "퀴즈",
    "title.nl": "Quiz",
    "title.th": "แบบทดสอบ",
    "description": "",
    "cq:movedTo": "",
    "tags": {}
    },
    "event-session": {
    "path": "/content/cq:tags/caas/content-type/event-session",
    "tagID": "caas:content-type/event-session",
    "name": "event-session",
    "tagImage": "",
    "title": "Event Session",
    "title.sv_se": "Event Session",
    "title.zh_cn": "活动环节",
    "title.ko_kr": "이벤트 세션",
    "title.pt": "SESSÃO DE EVENTO",
    "title.nl_nl": "GEBEURTENISSESSIE",
    "title.fr": "Événement session",
    "title.ja": "イベントセッション",
    "title.zh_hk": "活動會議",
    "title.zh_tw": "活動會議",
    "title.it": "Sessione",
    "title.ko": "이벤트 세션",
    "title.de": "Event Session",
    "title.es": "SESIÓN DEL EVENTO",
    "title.sv": "Eventsession",
    "title.nl": "Evenementsessie",
    "title.th": "เซสชันกิจกรรม",
    "description": "",
    "cq:movedTo": "",
    "tags": {}
    },
    "event": {
    "path": "/content/cq:tags/caas/content-type/event",
    "tagID": "caas:content-type/event",
    "name": "event",
    "tagImage": "",
    "title": "Event",
    "title.de": "Event",
    "title.zh_cn": "事件",
    "title.es": "Evento",
    "title.pt": "Evento",
    "title.fr": "Évènement",
    "title.sv": "Event",
    "title.ja": "イベント",
    "title.zh_tw": "活動",
    "title.it": "Evento",
    "title.ko": "이벤트",
    "title.nl": "Evenement",
    "title.th": "กิจกรรม",
    "description": "",
    "cq:movedTo": "",
    "tags": {}
    },
    "infographic": {
    "path": "/content/cq:tags/caas/content-type/infographic",
    "tagID": "caas:content-type/infographic",
    "name": "infographic",
    "tagImage": "",
    "title": "Infographic",
    "title.sv_se": "Infografik",
    "title.zh_cn": "信息图",
    "title.ko_kr": "인포그래픽",
    "title.pt": "Infográfico",
    "title.nl_nl": "Infographic",
    "title.fr": "Infographie",
    "title.ja": "インフォグラフィック",
    "title.zh_hk": "資訊圖表",
    "title.zh_tw": "資訊圖表",
    "title.it": "Infografica",
    "title.ko": "인포그래픽",
    "title.de": "Infographic",
    "title.es": "Infografía",
    "title.sv": "Infografik",
    "title.nl": "Infographic",
    "title.th": "อินโฟกราฟิก",
    "description": "",
    "cq:movedTo": "",
    "tags": {}
    },
    "ebook": {
    "path": "/content/cq:tags/caas/content-type/ebook",
    "tagID": "caas:content-type/ebook",
    "name": "ebook",
    "tagImage": "",
    "title": "eBook",
    "title.sv_se": "E-bok",
    "title.zh_cn": "电子书",
    "title.ko_kr": "e북",
    "title.pt": "eBook",
    "title.nl_nl": "E-book",
    "title.fr": "ebook",
    "title.ja": "電子ブック",
    "title.zh_hk": "電子書",
    "title.zh_tw": "電子書",
    "title.it": "ebook",
    "title.ko": "e북",
    "title.de": "E-Book",
    "title.es": "eBook",
    "title.sv": "e-bok",
    "title.nl": "E-book",
    "title.th": "อีบุ๊ก",
    "description": "",
    "cq:movedTo": "",
    "tags": {}
    },
    "demo": {
    "path": "/content/cq:tags/caas/content-type/demo",
    "tagID": "caas:content-type/demo",
    "name": "demo",
    "tagImage": "",
    "title": "Demo",
    "title.sv_se": "Demo",
    "title.zh_cn": "演示",
    "title.ko_kr": "데모",
    "title.pt": "Demonstração",
    "title.nl_nl": "Demo",
    "title.fr": "Démonstration ",
    "title.ja": "デモ",
    "title.zh_hk": "示範",
    "title.zh_tw": "示範",
    "title.it": "la demo",
    "title.ko": "데모",
    "title.de": "Demo",
    "title.es": "Demostración",
    "title.sv": "Demo",
    "title.nl": "Demo",
    "title.th": "ตัวอย่าง",
    "description": "",
    "cq:movedTo": "",
    "tags": {}
    },
    "event-speaker": {
    "path": "/content/cq:tags/caas/content-type/event-speaker",
    "tagID": "caas:content-type/event-speaker",
    "name": "event-speaker",
    "tagImage": "",
    "title": "Event Speaker",
    "description": "",
    "cq:movedTo": "",
    "tags": {}
    },
    "tutorial": {
    "path": "/content/cq:tags/caas/content-type/tutorial",
    "tagID": "caas:content-type/tutorial",
    "name": "tutorial",
    "tagImage": "",
    "title": "Tutorial",
    "title.de": "Tutorial",
    "title.zh_cn": "教程",
    "title.es": "Tutorial",
    "title.pt": "Tutorial",
    "title.fr": "Tutoriel",
    "title.sv": "Självstudiekurs",
    "title.ja": "チュートリアル",
    "title.zh_tw": "教學課程",
    "title.it": "Tutorial",
    "title.ko": "튜토리얼",
    "title.nl": "Tutorial",
    "title.th": "บทแนะนำ",
    "description": "",
    "cq:movedTo": "",
    "tags": {}
    },
    "product-tour": {
    "path": "/content/cq:tags/caas/content-type/product-tour",
    "tagID": "caas:content-type/product-tour",
    "name": "product-tour",
    "tagImage": "",
    "title": "Product Tour",
    "title.de": "Produkttour",
    "title.zh_cn": "产品导览",
    "title.es": "Recorrido por el producto",
    "title.pt": "Tour de produto",
    "title.fr": "Visite guidée du produit",
    "title.sv": "Produktrundtur",
    "title.ja": "製品ツアー",
    "title.zh_tw": "產品導覽",
    "title.it": "Presentazione del prodotto",
    "title.ko": "제품 둘러보기",
    "title.nl": "Productrondleiding",
    "title.th": "ทัวร์แนะนำผลิตภัณฑ์",
    "description": "",
    "cq:movedTo": "",
    "tags": {}
    },
    "template": {
    "path": "/content/cq:tags/caas/content-type/template",
    "tagID": "caas:content-type/template",
    "name": "template",
    "tagImage": "",
    "title": "Template",
    "title.de": "Vorlage",
    "title.zh_cn": "模板",
    "title.es": "Plantilla",
    "title.pt": "Modelo",
    "title.fr": "Modèle",
    "title.sv": "Mall",
    "title.ja": "テンプレート",
    "title.zh_tw": "範本",
    "title.it": "Modello",
    "title.ko": "템플릿",
    "title.nl": "Sjabloon",
    "title.th": "เทมเพลต",
    "description": "",
    "cq:movedTo": "",
    "tags": {}
    },
    "promotion": {
    "path": "/content/cq:tags/caas/content-type/promotion",
    "tagID": "caas:content-type/promotion",
    "name": "promotion",
    "tagImage": "",
    "title": "Promotion",
    "title.de": "Promotion",
    "title.zh_cn": "促销",
    "title.es": "Promoción",
    "title.pt": "Promoção",
    "title.fr": "Promotion",
    "title.sv": "Kampanj",
    "title.ja": "プロモーション",
    "title.zh_tw": "促銷",
    "title.it": "Promozione",
    "title.ko": "프로모션",
    "title.nl": "Promotie",
    "title.th": "การโปรโมต/โปรโมชัน",
    "description": "",
    "cq:movedTo": "",
    "tags": {}
    },
    "certification": {
    "path": "/content/cq:tags/caas/content-type/certification",
    "tagID": "caas:content-type/certification",
    "name": "certification",
    "tagImage": "",
    "title": "Certification",
    "title.de": "Zertifizierung",
    "title.zh_cn": "认证",
    "title.es": "Certificación",
    "title.pt": "Certificação",
    "title.fr": "Certification",
    "title.sv": "Certifiering",
    "title.ja": "認証",
    "title.zh_tw": "認證",
    "title.it": "Certificazione",
    "title.ko": "인증",
    "title.nl": "Certificering",
    "title.th": "การรับรอง",
    "description": "",
    "cq:movedTo": "",
    "tags": {}
    },
    "application": {
    "path": "/content/cq:tags/caas/content-type/application",
    "tagID": "caas:content-type/application",
    "name": "application",
    "tagImage": "",
    "title": "Application",
    "title.de": "Programm",
    "title.zh_cn": "应用",
    "title.es": "Aplicación",
    "title.pt": "Aplicativo",
    "title.fr": "Applications",
    "title.sv": "Programvara",
    "title.ja": "アプリケーション",
    "title.zh_tw": "應用",
    "title.it": "Applicazione",
    "title.ko": "애플리케이션",
    "title.nl": "Applicatie",
    "title.th": "แอปพลิเคชัน/การใช้/การสมัคร",
    "description": "",
    "cq:movedTo": "",
    "tags": {}
    },
    "podcast": {
    "path": "/content/cq:tags/caas/content-type/podcast",
    "tagID": "caas:content-type/podcast",
    "name": "podcast",
    "tagImage": "",
    "title": "Podcast",
    "title.de": "Podcast",
    "title.zh_cn": "播客",
    "title.es": "Podcast",
    "title.pt": "Podcast",
    "title.fr": "Podcast",
    "title.sv": "Podcast",
    "title.ja": "ポッドキャスト",
    "title.zh_tw": "播客",
    "title.it": "Podcast",
    "title.ko": "팟캐스트",
    "title.nl": "Podcast",
    "title.th": "พอดแคสต์",
    "description": "",
    "cq:movedTo": "",
    "tags": {}
    },
    "guide": {
    "path": "/content/cq:tags/caas/content-type/guide",
    "tagID": "caas:content-type/guide",
    "name": "guide",
    "tagImage": "",
    "title": "Guide",
    "title.sv_se": "Guide",
    "title.zh_cn": "指南",
    "title.ko_kr": "가이드",
    "title.pt": "Guia",
    "title.nl_nl": "Handleiding",
    "title.fr": "Guide ",
    "title.ja": "ガイド",
    "title.zh_hk": "指南",
    "title.zh_tw": "指南",
    "title.it": "Guida",
    "title.ko": "가이드",
    "title.de": "Leitfaden",
    "title.es": "Guía",
    "title.sv": "Guide",
    "title.nl": "Gids",
    "title.th": "คู่มือ",
    "description": "",
    "cq:movedTo": "",
    "tags": {}
    },
    "consulting": {
    "path": "/content/cq:tags/caas/content-type/consulting",
    "tagID": "caas:content-type/consulting",
    "name": "consulting",
    "tagImage": "",
    "title": "Consulting",
    "title.de": "Consulting",
    "title.zh_cn": "咨询",
    "title.es": "Consultoría",
    "title.pt": "Consultoria",
    "title.fr": "Conseil",
    "title.sv": "Konsulttjänster",
    "title.ja": "コンサルティング",
    "title.zh_tw": "諮詢",
    "title.it": "Consulenza",
    "title.ko": "컨설팅",
    "title.nl": "Consulting",
    "title.th": "การให้คำปรึกษา",
    "description": "",
    "cq:movedTo": "",
    "tags": {}
    },
    "product": {
    "path": "/content/cq:tags/caas/content-type/product",
    "tagID": "caas:content-type/product",
    "name": "product",
    "tagImage": "",
    "title": "Product",
    "title.de": "Produkt",
    "title.zh_cn": "产品",
    "title.es": "Producto",
    "title.pt": "Produto",
    "title.fr": "Produit",
    "title.sv": "Produkt",
    "title.ja": "製品",
    "title.zh_tw": "產品",
    "title.it": "Prodotto",
    "title.ko": "제품",
    "title.nl": "Product",
    "title.th": "ผลิตภัณฑ์",
    "description": "",
    "cq:movedTo": "",
    "tags": {}
    },
    "partner": {
    "path": "/content/cq:tags/caas/content-type/partner",
    "tagID": "caas:content-type/partner",
    "name": "partner",
    "tagImage": "",
    "title": "Partner",
    "title.de": "Partner",
    "title.zh_cn": "合作伙伴",
    "title.es": "Partner",
    "title.pt": "Parceiro",
    "title.fr": "Partenaire",
    "title.sv": "Partner",
    "title.ja": "パートナー",
    "title.zh_tw": "合作夥伴",
    "title.it": "Partner",
    "title.ko": "파트너",
    "title.nl": "Partner",
    "title.th": "พาร์ทเนอร์",
    "description": "",
    "cq:movedTo": "",
    "tags": {}
    },
    "solution": {
    "path": "/content/cq:tags/caas/content-type/solution",
    "tagID": "caas:content-type/solution",
    "name": "solution",
    "tagImage": "",
    "title": "Solution",
    "title.de": "Lösung",
    "title.zh_cn": "解决方案",
    "title.es": "Solución",
    "title.pt": "Solução",
    "title.fr": "Solution",
    "title.sv": "Lösning",
    "title.ja": "ソリューション",
    "title.zh_tw": "解決方案",
    "title.it": "Soluzione",
    "title.ko": "솔루션",
    "title.nl": "Oplossing",
    "title.th": "โซลูชัน",
    "description": "",
    "cq:movedTo": "",
    "tags": {}
    },
    "course": {
    "path": "/content/cq:tags/caas/content-type/course",
    "tagID": "caas:content-type/course",
    "name": "course",
    "tagImage": "",
    "title": "Course",
    "title.sv_se": "Kurs",
    "title.zh_cn": "课程",
    "title.ko_kr": "강의",
    "title.pt": "Curso",
    "title.nl_nl": "Cursus",
    "title.fr": "Cours",
    "title.ja": "コース",
    "title.zh_hk": "課程單元",
    "title.zh_tw": "課程單元",
    "title.it": "Corso",
    "title.ko": "강의",
    "title.de": "Kurs",
    "title.es": "Curso",
    "title.sv": "Kurs",
    "title.nl": "Cursus",
    "title.th": "หลักสูตร",
    "description": "",
    "cq:movedTo": "",
    "tags": {}
    },
    "document": {
    "path": "/content/cq:tags/caas/content-type/document",
    "tagID": "caas:content-type/document",
    "name": "document",
    "tagImage": "",
    "title": "Document",
    "description": "",
    "cq:movedTo": "",
    "tags": {}
    },
    "solution-brief": {
    "path": "/content/cq:tags/caas/content-type/solution-brief",
    "tagID": "caas:content-type/solution-brief",
    "name": "solution-brief",
    "tagImage": "",
    "title": "Solution brief",
    "description": "",
    "cq:movedTo": "",
    "tags": {}
    },
    "how-to": {
    "path": "/content/cq:tags/caas/content-type/how-to",
    "tagID": "caas:content-type/how-to",
    "name": "how-to",
    "tagImage": "",
    "title": "How-to",
    "description": "",
    "cq:movedTo": "",
    "tags": {}
    },
    "white-paper": {
    "path": "/content/cq:tags/caas/content-type/white-paper",
    "tagID": "caas:content-type/white-paper",
    "name": "white-paper",
    "tagImage": "",
    "title": "White paper",
    "description": "",
    "cq:movedTo": "",
    "tags": {}
    },
    "plans-&-pricing": {
    "path": "/content/cq:tags/caas/content-type/plans-&-pricing",
    "tagID": "caas:content-type/plans-&-pricing",
    "name": "plans-&-pricing",
    "tagImage": "",
    "title": "Plans &amp; Pricing",
    "description": "",
    "cq:movedTo": "",
    "tags": {}
    },
    "features": {
    "path": "/content/cq:tags/caas/content-type/features",
    "tagID": "caas:content-type/features",
    "name": "features",
    "tagImage": "",
    "title": "Features",
    "description": "",
    "cq:movedTo": "",
    "tags": {}
    },
    "progressive-offer": {
    "path": "/content/cq:tags/caas/content-type/progressive-offer",
    "tagID": "caas:content-type/progressive-offer",
    "name": "progressive-offer",
    "tagImage": "",
    "title": "Progressive Offer",
    "description": "This tag is used for DX demand offers that follow a very specific order and cadence. This tag is usually excluded from the Resource Center.",
    "cq:movedTo": "",
    "tags": {}
    },
    "financial-services": {
    "path": "/content/cq:tags/caas/content-type/financial-services",
    "tagID": "caas:content-type/financial-services",
    "name": "financial-services",
    "tagImage": "",
    "title": "Financial Services",
    "description": "",
    "cq:movedTo": "",
    "tags": {}
    },
    "partner-story": {
    "path": "/content/cq:tags/caas/content-type/partner-story",
    "tagID": "caas:content-type/partner-story",
    "name": "partner-story",
    "tagImage": "",
    "title": "Partner Story",
    "description": "",
    "cq:movedTo": "",
    "tags": {}
    },
    "product-page": {
    "path": "/content/cq:tags/caas/content-type/product-page",
    "tagID": "caas:content-type/product-page",
    "name": "product-page",
    "tagImage": "",
    "title": "Product Page",
    "description": "",
    "cq:movedTo": "",
    "tags": {}
    }
    }
    },
    "cta": {},
    "badge": {},
    "card-style": {},
    "business-unit": {},
    "journey-phase": {},
    "role": {},
    "industry": {},
    "events": {},
    "gated": {},
    "country": {},
    "language": {},
    "source": {},
    "products": {},
    "product-categories": {},
    "mnemonics": {},
    "audience": {},
    "topic": {},
    "technical-level": {},
    "features": {},
    "availability": {},
    "business-size": {},
    "collection": {},
    "customer-story-type": {},
    "form": {},
    "region": {},
    "related-product": {},
    "summit": {}
    }
    }
    }
    }
}
